#############################################################################
# Makefile for building: diplom
# Generated by qmake (2.01a) (Qt 4.8.0) on: Wed May 16 04:48:10 2012
# Project:  diplom.pro
# Template: app
# Command: /home/dmitry/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec ../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile diplom.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -I. -I../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtDeclarative -I../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/include -Iqmlapplicationviewer -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/dmitry/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/dmitry/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/lib -lglut -lGLU -lQtDeclarative -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/dmitry/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = utils.cpp \
		main.cpp \
		drow_utils.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp
OBJECTS       = utils.o \
		main.o \
		drow_utils.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o
DIST          = ../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		diplom.pro
QMAKE_TARGET  = diplom
DESTDIR       = 
TARGET        = diplom

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: diplom.pro  ../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf ../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile diplom.pro
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../Applications/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile diplom.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/diplom1.0.0 || $(MKDIR) .tmp/diplom1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/diplom1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h types.h utils.h drow_utils.h .tmp/diplom1.0.0/ && $(COPY_FILE) --parents utils.cpp main.cpp drow_utils.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/diplom1.0.0/ && (cd `dirname .tmp/diplom1.0.0` && $(TAR) diplom1.0.0.tar diplom1.0.0 && $(COMPRESS) diplom1.0.0.tar) && $(MOVE) `dirname .tmp/diplom1.0.0`/diplom1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/diplom1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/home/dmitry/Applications/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

utils.o: utils.cpp utils.h \
		types.h \
		drow_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

main.o: main.cpp utils.h \
		types.h \
		drow_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

drow_utils.o: drow_utils.cpp utils.h \
		types.h \
		drow_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drow_utils.o drow_utils.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/diplom/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/diplom/qml/ 
	-$(INSTALL_DIR) /home/dmitry/Projects/diplom/qml/diplom $(INSTALL_ROOT)/opt/diplom/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/diplom/qml/diplom
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/diplom/qml/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/diplom/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/diplom/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/diplom/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/diplom/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/diplom/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/diplom/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

